name: build

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ['1.18', '1.19', '1.20']

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: run tests
        run: |
          export PATH="$(go env GOPATH)/bin:${PATH}"
          make install.tools
          make .gitvalidation
          make docs conformance
